import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav } from "react-day-picker";
import Navbar from "@/components/utils/Navbar";

// 1. Configure Fonts
const instrumentSerifHeading = Instrument_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-heading'
});

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-sans'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     suppressHydrationWarning={true}  // Recommended when using dark mode/themes
      className=
        "h-full antialiased scroll-smooth dark "
    >
      <body className="h-full flex flex-col "> 
        {/* Navbar Container */}
        <header className="shrink-0 z-50"> 
          <Navbar />
        </header>
      <main className="flex-1 relative mx-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}